### ISSUE TITLE
Hints are not displayed under the checkbox option that they are attached to

### ISSUE THREAD

**Issue by Mankro** [apluslms/mooc-grader#110]
Some changes during the spring 2021 have broken the hints feature in questionnaires. The hints in checkbox questions are not rendered under the checkbox option, but always under all options. In A+ v1.8 (January 2021), we just got a new improvement and the hints were shown under each checkbox so that it is easier to see which checkbox triggered the hint.

I am also uncertain if the hints are sometimes missing and not rendered at all when they should be visible.

Screenshot from A+ v1.8 (January 2021) in the aplus-manual course. Notice that the checkbox hints are rendered right under each checkbox.
![image](https://user-images.githubusercontent.com/6130378/117654589-9eacb580-b19e-11eb-8702-f696b012b608.png)

![image](https://user-images.githubusercontent.com/6130378/117655070-432ef780-b19f-11eb-89b3-ca84c20b5ee8.png)

**Comment by Mankro** [comment]
Nice catch. I didn't see the problem in hints when I upgraded Django. What could go wrong with the Django upgrade:
* there may be minor changes in the Form API. The questionnaire grading uses a Django form: https://github.com/apluslms/mooc-grader/blob/master/access/types/forms.py
* the code for hints are messy and it even mixes types. The `hints` variable is sometimes a list and sometimes a dictionary. As far as I remember, it was necessary to use dictionaries for the improved checkbox hints so that they can be rendered under the checkbox. But most of the code uses a `hints` list: https://github.com/apluslms/mooc-grader/blob/f86856b2f8d77578a802d88ca10f6d64eed9a805/access/types/forms.py#L351-L360
  https://github.com/apluslms/mooc-grader/blob/f86856b2f8d77578a802d88ca10f6d64eed9a805/access/types/forms.py#L566
* The Django template syntax has also changed. I remember that Django 1.9 did not support some combination of logical operators (`and`, `or`, `not`) in the same `if` condition. Django 2.2 is more flexible and supports more complex logical expressions.

**Comment by skulonen** [comment]
The problem lies in `graded_form.html`. Before the upgrade, the line `{% for choice in field %}` yielded `CheckboxChoiceInput` instances, but after the upgrade it yields `BoundWidget` instances. The template rendering relied on the `value` and `choice_value` attributes of the `CheckboxChoiceInput` but these aren't available in the `BoundWidget`class. I'll try to update the template so that it works with the new class.
