### ISSUE TITLE
File upload exercises may use duplicate id attributes in HTML

### ISSUE THREAD

**Issue by Mankro** [apluslms/mooc-grader#111]
When you have multiple file upload exercises (`view_type: access.types.stdasync.acceptFiles` in the exercise config.yaml) in the same chapter page, the file forms may use the same field name in the exercise config.yaml file. **The HTML forms then use identical id attribute values** in the same document. This breaches the HTML specs and also causes accessibility problems since the form labels also refer to the form field by id.

https://github.com/apluslms/aplus-manual/blob/d159a62e9920a915232e45338c2560ee2650c70c/exercises/hello_python/config.yaml#L11

Could we randomize the id attributes so that they are not identical in different exercises even if the field names are identical? My gut feeling says that changing the id attributes would not break anything since I don't think our code really refers to those ids elsewhere.

We have already randomized ids in questionnaires:
https://github.com/apluslms/mooc-grader/blob/5019bceab531dfe4e35c9eb8e60cb4cc343f8e56/access/types/forms.py#L46

**Comment by Mankro** [comment]
This issue is a more specific version, mostly a duplicate, of https://github.com/apluslms/a-plus/issues/593

**Comment by Mankro** [comment]
There are multiple view_types that have the same problem with id attributes:
* https://github.com/apluslms/mooc-grader/blob/5019bceab531dfe4e35c9eb8e60cb4cc343f8e56/access/types/stdasync.py#L52
* https://github.com/apluslms/mooc-grader/blob/5019bceab531dfe4e35c9eb8e60cb4cc343f8e56/access/templates/access/accept_post_form.html#L6

* https://github.com/apluslms/mooc-grader/blob/5019bceab531dfe4e35c9eb8e60cb4cc343f8e56/access/types/stdasync.py#L84
* https://github.com/apluslms/mooc-grader/blob/5019bceab531dfe4e35c9eb8e60cb4cc343f8e56/access/templates/access/accept_files_form.html#L14

* https://github.com/apluslms/mooc-grader/blob/5019bceab531dfe4e35c9eb8e60cb4cc343f8e56/access/types/stdasync.py#L204
* https://github.com/apluslms/mooc-grader/blob/5019bceab531dfe4e35c9eb8e60cb4cc343f8e56/access/templates/access/accept_general_form.html#L31

**Comment by skulonen** [comment]
@Mankro The problem also exists with active element exercises, whose forms are constructed by Javascript code instead of mooc-grader.

In fact, the problem is even worse because the label's `for` and the input's `id` attributes don't match. For example, in the Exponential distribution exercise, the label's `for` attribute is `exponentlambdain_input` but the input's `id` is `exponentlambdain_input_id`. Should we open a new issue for the active elements?

**Comment by Mankro** [comment]
Created the new issue https://github.com/apluslms/a-plus/issues/823, but it is not urgent now because active elements are very rarely used anywhere.
