### ISSUE TITLE
Critical config key error (with i18n?)

### ISSUE THREAD

**Issue by teemulehtinen** [apluslms/mooc-grader#13]
Manifests regularly but inconsistently in production but only on the course that uses the |i18n configuration modifier. After some time the dict received from config is just missing a key, such as form field title: http://www.cs.hut.fi/~lehtint6/graderkeyerr.html

Temprary fix: uwsgi reload (touch /etc/uwsgi/grader.ini)

**Comment by Mankro** [comment]
This PR in a-plus-rst-tools may be related to this:
https://github.com/Aalto-LeTech/a-plus-rst-tools/pull/52

This hotfix in the mooc-grader also affects cases when a plain field is defined in JSON in addition to the i18n version (both `title` and `title|i18n`): https://github.com/Aalto-LeTech/mooc-grader/commit/a1c80ab46879818d39049d09a5d52514198a00b2

**Comment by Mankro** [comment]
I think this old issue has been resolved.
