### ISSUE TITLE
Course feedback questionnaire template looks odd with required questions

### ISSUE THREAD

**Issue by PasiSa** [apluslms/mooc-grader#142]
The asterisk indicating the required questions shows on separate line from the question, but it would be better to have them on the same line. Below is an example from CS-E4730 course

![image](https://user-images.githubusercontent.com/3129064/221189061-9a2da0c0-a21c-4752-be38-d00e1549eb40.png)

**Comment by EerikSaksi** [comment]
I'll start working on this unless someone is already doing it
