### ISSUE TITLE
Setup instructions for Kubernetes?

### ISSUE THREAD

**Issue by FeldrinH** [apluslms/mooc-grader#153]
The introduction in the readme of this repo says:

> If the number of submissions is large, we recommend setting up a **Kubernetes** cluster for the grader.

This seems to imply that mooc-grader somehow works in/with Kubernetes, yet I could not find any instructions for how to actually install it in a Kubernetes cluster. Where can I find these instructions?

**Comment by Mankro** [comment]
We haven't published any instructions for the Kubernetes deployment. We have Helm charts for it, but they haven't been cleaned up so that they could be published. I can ask around if someone could get it done. Though, our own deployment includes some details that are specific to our local needs.

**Comment by Mankro** [comment]
I have created these new, empty git repos for the public version of the Kubernetes deployment instructions and files. It may take some weeks before we have finished the public version.

* https://github.com/apluslms/aplus-helm-chart
* https://github.com/apluslms/aplus-deployment-container-images

**Comment by Mankro** [comment]
The Helm charts have been added there. The container images are still under construction.

**Comment by Mankro** [comment]
The container image git repo has been updated too. Closing the issue now.
