### ISSUE TITLE
Highlight selected option in questionnaires 

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/mooc-grader#53]
> **Migrated from Trello**

In quizzes, the radio button or checkbox can be selected by clicking on the text label instead of the button itself. This may lead to accidents since it is easy to click some text while scrolling through the page. We probably want to keep the labels as clickables, but the UI should make it clearer to the student when they have selected something. For example, the selected checkbox and its label could have a background colour and the colour could be animated at the moment of the click so that it stands out.

**Comment by skulonen** [comment]
@Mankro Would this be an acceptable style of highlighting? There's a light blue rounded rectangle underneath the currently focused option, and it also pops out/enlarges briefly at the moment of selection, drawing attention to the selection.
![image](https://user-images.githubusercontent.com/28843787/116877239-5af9ff00-ac26-11eb-9510-0cbb83daa04e.png)

**Comment by Mankro** [comment]
@skulonen yes, that is good! What if the text is also bolded a bit (CSS font-weight)? Makes sense or not?

**Comment by skulonen** [comment]
@Mankro Yeah, that could work. Now that I think about it, should we highlight all currently checked options, or just the currently focused one? I've implemented the latter, but I could change it to highlight all checked options.

**Comment by Mankro** [comment]
@skulonen Let's highlight all selected options!

**Comment by skulonen** [comment]
This was fixed by commits https://github.com/apluslms/a-plus/commit/844588ab7272a5c70e05c18fb2b35e3076f6c83f and https://github.com/apluslms/mooc-grader/commit/eae1040afc80209ea3e3123716ad3468590f055c. The commits were linked to the wrong issue, which is why I am closing this manually.
