### ISSUE TITLE
Questionnaire model answer shows neutral choices as incorrect

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/mooc-grader#55]
> **Migrated from Trello**

When you press the A+ "show model answer" button in a questionnaire exercise, it shows the neutral choices of checkbox questions as incorrect. There is no visual separation between incorrect and neutral choices.

**Comment by annirytkonen** [comment]
this should be moved to MOOC grader

**Comment by Mankro** [comment]
I had a feeling that this was fixed in December 2019, but it must be checked.
