### ISSUE TITLE
gitmanager: Define env value STATIC_CONTENT_HOST

### ISSUE THREAD

**Issue by raphendyr** [apluslms/mooc-grader#57]
Define `STATIC_CONTENT_HOST` in `gitmanager/cron_pull_build.sh`, so that A+ and RST build can start to rely on it. Currently, both of those have hacks to go around the issue. Main goal is to ease the migration by allowing us to start developing tools, while still using the old deployment tool (gitmanager).

In a long run, static material will be moved to private or public CDN, thus it will not be in a same place as the course chapter html or exercises.

**Comment by raphendyr** [comment]
Related to #31

**Comment by Mankro** [comment]
The new gitmanager service in A+ v1.12 defines `STATIC_CONTENT_HOST`.

https://github.com/apluslms/gitmanager/blob/912a7fceff8b232445bbe6cb6d5791f2f4daccf3/builder/builder.py#L112
