### ISSUE TITLE
MOOC-grader leaks secret chapters to the web

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/mooc-grader#63]
>**Migrated from Trello**

All chapter content is compiled in the MOOC-grader and served to the web from the `_build/html` directory. However, since some chapters have restricted visibility in A+, it makes no sense that their content is served to the public web from the MOOC-grader. The content should not be available to the web in the MOOC-grader since it is supposed to be served via A+ and follow access restrictions in A+ (where the user has been authenticated and restrictions can be applied).

**Comment by Mankro** [comment]
Blocked by: the Shepherd project and/or a new solution for serving chapter HTML files and static files to A+.

MOOC-Grader won't be fixed, but the chapter HTML files and the gitmanager will be removed from it.

**Comment by Mankro** [comment]
The new gitmanager project should solve this issue.

**Comment by Mankro** [comment]
Closing because the new Git Manager fixed this.
https://github.com/apluslms/gitmanager/blob/365b1c7d9fbd40f8503d7addfa3ae6e2062bbfa1/access/views.py#L101
