### ISSUE TITLE
Support (much) faster Scala compilations

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/mooc-grader#68]
>**Migrated from Trello**

At least as "fast" as we used to have before containerization. (Currently, even the most trivial Scala program takes dozens of seconds or even more than a minute to compile.)

**Comment by jsorva** [comment]
This is essentially a duplicate of this issue in the MOOC Grader repo, which I suppose is the correct place for this: https://github.com/apluslms/mooc-grader/issues/141
