### ISSUE TITLE
Add the .editorconfig file

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/mooc-grader#83]
The .editorconfig file will support the style guides defined for the A+ projects https://apluslms.github.io/contribute/styleguides/

**Comment by MSTEWARDSON** [comment]
Hello, I would like to add the .editorconfig file to the project. From what I'm reading and understanding the series of A+ projects all use a predefined .editorconfig file that this project is currently missing. Would it simply be adding that file to this project? Im quite new to open-source development, and just learning about these .editorconfig files.
