### ISSUE TITLE
Fix hints bug in questionnaire: mixing list and dict syntax

### ISSUE THREAD

**Issue by Mankro** [apluslms/mooc-grader#88]
The `hints` variable in `grade_field` looks suspicious. Some lines use it like a list and some lines like a dict. My first impression is that it should be a list.

This line crashes for me:

https://github.com/apluslms/mooc-grader/blob/50d1e2a4f65b999480e472fb1ae9250d7b0f8bde/access/types/forms.py#L639

```
File "/srv/grader/access/types/forms.py", line 639, in grade_field
     hints['multiple'] = _('Multiple choices are selectable')
     TypeError: list indices must be integers or slices, not str
```

**Comment by Mankro** [comment]
Is it enough to change the dict syntax to the list append method?

**Comment by Mankro** [comment]
This crash occurs in the arithmetic quiz in the test-course (indexyaml branch): https://github.com/apluslms/test-course/blob/6b19b9e1a6c523516812950ae7c3ae499e828bc2/exercises/arithmetic.yaml

**Comment by jaguarfi** [comment]
> This changed the datatype of the `hints`, which makes the code a bit messy, i.e., it type isn't consistent in different locations of the code. Would it be possible to always convert the list of hints to a OrderedDict? ( `hints = OrderedDict.from_keys(hints)` )

_Originally posted by @raphendyr in https://github.com/apluslms/mooc-grader/pull/76#r457938971_
