### ISSUE TITLE
The editor used in the tietokannat course is broken

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/mooc-grader#95]
>After A+ update, the editor which is used to write relational algebra expressions seems not to work. For example, if you go to CS-1150 summer course 2020 and choose Exercise Round 1, Problem 1 and try to write the answer pushing any of the buttons for different operators does not produce any result. I have tried with Firefox and Chrome. These properties used to work without any problems before the update.
>
>Writing the expression yourself with letters (keys) still works, but that is too tedious for the students.
>
>This editor is essential for our course. The course starts on February 8th.
>
>Kerttu

The editor used in the Tietokannat course is broken due to some changes added in the commit https://github.com/apluslms/mooc-grader/commit/6dde039f24b55cebc327086c81aaaa226506faa2 and more specifically in the [line 46](https://github.com/apluslms/mooc-grader/blob/6dde039f24b55cebc327086c81aaaa226506faa2/access/types/forms.py#L46.)

The editor used in the aforementioned course selects the `<textarea>` element by using the jquery selector `$('#id_answer")` which unfortunately is changed by [line 46](https://github.com/apluslms/mooc-grader/blob/6dde039f24b55cebc327086c81aaaa226506faa2/access/types/forms.py#L46.) 

One solution can be to add some validations before changing the `id` value, here in the mooc-grader, or use the name parameter to select the `<textarea>` element in the **editor.js** file used in the Tietokannat course

**Editor**
![image](https://user-images.githubusercontent.com/10437475/104019013-777bb280-51c3-11eb-8cd5-7623ec86dc42.png)

**Comment by Mankro** [comment]
@jaguarfi  perhaps this JS click event handler bug breaks the JavaScript in this course too. At first, I think it is likely.
https://github.com/apluslms/a-plus/pull/736

**Comment by jaguarfi** [comment]
I am not really sure, the editor uses buttons and therefore the event handler will not be added to the button. Besides, the error that I found in the google developer console shows that the `id="id_answer"` in the `<textarea>` element is not found. What I found is that the **id** is changed to values, such as `id="exercise-QUFIjB5k-answer"` and `id="exercise-T1hpuEuH-answer"`. I verified with version 1.7 of the mooc-grader and the id remains the same (i.e. `id="id_answer"`, so I am pretty sure that the error is introduced in the [line 46](https://github.com/apluslms/mooc-grader/blob/6dde039f24b55cebc327086c81aaaa226506faa2/access/types/forms.py#L46.)

**Comment by Mankro** [comment]
@jaguarfi yes indeed. The course configuration defines the field names like `answer`. In A+ v1.7, that guaranteed the form HTML id `id_answer`, but the HTML ids have a randomized part. Could the JavaScript in the Databases course be changed so that it will find all elements with id `exercise-*-answer` where `*` is not known?

**Comment by jaguarfi** [comment]
This [commit](https://version.aalto.fi/gitlab/course/tietokannat/-/commit/094a40373af0c949af3fa1bf23fda7bfb57f2cd1#bb1af8bb3f8f38de05c69b7c8d1d173ae65bdaf4_310_309)[Internal link] should fix this issue.

**Comment by Mankro** [comment]
@jaguarfi Great! You can close this issue when you think the course JS code has been fixed and git-pushed.
